# Generated by Django 4.2.2 on 2023-06-28 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_sw', models.CharField(choices=[('lesson', 'Lesson'), ('consultation', 'Consultation')], max_length=20, verbose_name='Type')),
                ('homework', models.TextField(blank=True, null=True, verbose_name='Homework')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('date_sw', models.DateField(verbose_name='Date of sw')),
                ('time_sw', models.TimeField(choices=[(datetime.time(10, 0), '10:00'), (datetime.time(11, 0), '11:00'), (datetime.time(12, 0), '12:00'), (datetime.time(13, 0), '13:00'), (datetime.time(14, 0), '14:00'), (datetime.time(15, 0), '15:00'), (datetime.time(16, 0), '16:00')], verbose_name='Time of sw')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Confirmed')),
            ],
        ),
    ]
